apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trade-marshals-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: trade-marshals-alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    # Enable CORS for all origins (for development)
    alb.ingress.kubernetes.io/actions.cors-headers: |
      {
        "type": "fixed-response",
        "fixedResponseConfig": {
          "statusCode": "200",
          "contentType": "text/plain",
          "messageBody": "OK"
        },
        "forwardConfig": {
          "targetGroups": []
        }
      }
spec:
  rules:
    # Frontend (Angular) - Main domain
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angular-app-svc
                port:
                  number: 80
    
    # API Routes
    - http:
        paths:
          # Midtier API
          - path: /api/client
            pathType: Prefix
            backend:
              service:
                name: mid-nodejs-svc
                port:
                  number: 4000
          - path: /api/portfolio
            pathType: Prefix
            backend:
              service:
                name: mid-nodejs-svc
                port:
                  number: 4000
          - path: /api/trade
            pathType: Prefix
            backend:
              service:
                name: mid-nodejs-svc
                port:
                  number: 4000
          - path: /api/activity-report
            pathType: Prefix
            backend:
              service:
                name: mid-nodejs-svc
                port:
                  number: 4000
          - path: /api/client-preferences
            pathType: Prefix
            backend:
              service:
                name: mid-nodejs-svc
                port:
                  number: 4000
          
          # Spring Boot Backend (direct access if needed)
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: spring-app-svc
                port:
                  number: 8080
          
          # FMTS API
          - path: /fmts
            pathType: Prefix
            backend:
              service:
                name: fmts-nodejs-svc
                port:
                  number: 3000
